apiVersion: v1
kind: Pod
metadata:
  name: claire-test-suite
spec:
  containers:
    - name: claire-test-suite
      image: quay.io/rhmessagingqe/claire:latest
      command: ["mvn", "test", "-Dmaven.main.skip=true", "-Dtest=SmokeTests"]
      env:
        - name: OCP_API_URL
          valueFrom:
            secretKeyRef:
              name: ocp-config
              key: ocp-url
        - name: OCP_USERNAME
          valueFrom:
            secretKeyRef:
              name: ocp-config
              key: ocp-username
        - name: OCP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ocp-config
              key: ocp-password
