---
apiVersion: v1
kind: ConfigMap
metadata:
  name: run-script
  namespace: ${NAMESPACE}
data:
  run.sh: |-
    #!/usr/bin/env bash

    TEST_RESULTS_DIR="/app/test-results"
    OPERATOR_TEST_RESULTS_DIR="$${TEST_RESULTS_DIR}/operator-suite"
    BUILD_PROPERTIES="build_properties.yaml"
    CLAIRE_PROPERTIES="claire_properties.yaml"
    LOG_FILE="$${TEST_RESULTS_DIR}/tests.execution.log"

    function log() {
        if [[ "$$1" == "" ]]; then
          echo "$$1" | tee -a "$${LOG_FILE}"
        else
          echo "[$$(date "+%Y-%m-%d %H:%M:%S %z")] - $$1" | tee -a "$${LOG_FILE}"
        fi
    }

    log ""
    log "Creating test-results directory: $${OPERATOR_TEST_RESULTS_DIR}"
    mkdir -p "$${OPERATOR_TEST_RESULTS_DIR}"
    log ""
    log "Copying $${BUILD_PROPERTIES} to $${TEST_RESULTS_DIR}"
    cp "$${BUILD_PROPERTIES}" "$${TEST_RESULTS_DIR}"
    log ""
    log "Build properties:"
    log "$$(cat $${BUILD_PROPERTIES})"
    log ""
    log "Copying $${CLAIRE_PROPERTIES} to $${TEST_RESULTS_DIR}"
    cp "$${CLAIRE_PROPERTIES}" "$${TEST_RESULTS_DIR}"
    log ""
    log "Claire properties:"
    log "$$(cat $${CLAIRE_PROPERTIES})"
    log ""
    log "Starting Claire execution at $$(date)" | tee "$${TEST_RESULTS_DIR}/tests.execution.started"
    log ""
    log "Executing make with params: ${MAKE_TARGET}"
    make ${MAKE_TARGET} | tee -a "$${LOG_FILE}"
    log ""
    log "Finished Claire execution $$(date)" | tee "$${TEST_RESULTS_DIR}/tests.execution.completed"
    log ""
    log "sleeping forever"
    log ""
    sleep 99d